version: 2

models:
  - name: stg_shaved_ice
    description: "Staging: Raw Shaved Ice Parquet loaded with renamed columns"
    columns:
      - name: timestamp
        description: "Hour of the usage record (from USAGE_HOUR)"
      - name: region
        description: "Region identifier (from REGION_NUM)"
      - name: instance_type
        description: "VM instance type"
      - name: demand
        description: "Normalized usage/demand (from NORM_USAGE)"

  - name: int_daily_demand
    description: "Intermediate: Hourly data aggregated to daily with time features"
    columns:
      - name: date
        description: "Date of the observation"
      - name: daily_demand_total
        description: "Total demand for the day"
      - name: demand_rolling_7d_avg
        description: "7-day rolling average of daily demand"

  - name: mart_forecast_input
    description: "Mart: Final analysis-ready table for Python forecasting"
    columns:
      - name: date
        description: "Date of the observation"
        tests:
          - not_null
      - name: demand
        description: "Target variable: total daily demand"
        tests:
          - not_null
      - name: safety_stock_95pct
        description: "Safety stock buffer for 95% service level"

  - name: mart_stockout_events
    description: "Mart: Records of days where demand exceeded a defined capacity limit (p95 level)"
    columns:
      - name: date
        description: "Date of the stockout event"
      - name: region
        description: "Region where the event occurred"
      - name: instance_type
        description: "Type of instance"
      - name: demand
        description: "Total daily demand observed"
      - name: daily_demand_max
        description: "Peak hourly demand observed on this date"
      - name: capacity_limit_p95
        description: "Estimated capacity based on p95 of historical demand"
      - name: severity_pct
        description: "Percentage by which max demand exceeded capacity"
