version: 2

models:
  - name: stg_shaved_ice
    description: "Staging layer: Raw Shaved Ice CSV loaded into DuckDB with data quality flags"
    columns:
      - name: data_quality_flag
        description: "Row-level quality indicator: 'valid' or 'invalid'"
        tests:
          - accepted_values:
              values: ['valid']

  - name: int_daily_demand
    description: "Intermediate layer: Hourly data aggregated to daily with time features"
    columns:
      - name: date
        description: "Date of the observation"
        tests:
          - unique
          - not_null
      - name: daily_demand_total
        description: "Total VM demand for the day"
      - name: is_weekend
        description: "1 if Saturday or Sunday, 0 otherwise"
      - name: demand_rolling_7d_avg
        description: "7-day rolling average of daily demand"

  - name: mart_forecast_input
    description: "Mart layer: Final analysis-ready table for Python forecasting models"
    columns:
      - name: date
        description: "Date of the observation"
        tests:
          - unique
          - not_null
      - name: demand
        description: "Target variable: total daily VM demand"
        tests:
          - not_null
      - name: safety_stock_95pct
        description: "Safety stock buffer for 95% service level (1.96 * std dev)"
      - name: complete_day_flag
        description: "1 if all 24 hourly records present, 0 otherwise"
